### PR TITLE
Add labelAfterField option when rendering

### PR DESCRIPTION
**Pull request by semarketir**
Hi @ljharb

Would you review for this PR? :-)

Thank you ~ 🍺

### CODE REVIEW

**Comment by ljharb** [comment]
When was this feature removed?

**Comment by semarketir** [comment]
@ljharb Ah, Sorry.. I was mistaken about feature removed.

**Comment by ljharb** [comment]
@semarketir this looks great! Would you mind also adding this new option to the readme?

**Comment by semarketir** [comment]
@ljharb Ah.. Thank you ~
Okay, I'll add it on the readme :)

**Comment by semarketir** [comment]
@ljharb I've done for it, please check it out :-)

**Comment by semarketir** [comment]
@ljharb I've done, please check it out :-)

**Comment by ljharb** [comment]
@semarketir Can you rebase this down to a single commit? (ideally, with `[New]` prefixing the commit message

**Comment by semarketir** [comment]
@ljharb Done 🍻

**Comment by semarketir** [comment]
@ljharb Thank you bro ! 🍺

**Pull request merged**
