### PR TITLE
Replace email validator

### PR DESCRIPTION
**Pull request by thusoy**
This limits emails to "sane" emails which doesn't allow legacy features like quoted parts, comments, etc. This is more likely to be what people actually expect in an email address.

### CODE REVIEW

**Comment by ljharb** [comment]
Seems like the comment test is still failing.

**Comment by thusoy** [comment]
Yes, it fails because you overwrote my changes to that test. The old validator was unable to validate comments, this one does. I modified the test to accomodate that, but you removed those changes.

**Comment by ljharb** [comment]
I'm confused. There's now a test on master (yours) that includes comments, that passes on master. It shouldn't require modification in this PR to pass here, but it fails here.

For example, here is one of yours: https://github.com/caolan/forms/commit/0d7ec0100b7f22c70e97771f5158a4621cc1dd62#diff-b5c163a3676f9b1a4e6c960d07a2eeaeR174 and here's the same test pulled into master: https://github.com/caolan/forms/blob/master/test/test-validators.js#L174.

If I accidentally lost important changes, my apologies - could you restore them?

**Comment by thusoy** [comment]
Yes, that test asserts that emails with comments shouldn't be allowed since the regex didn't validate them, but those addresses are RFC compliant, thus when swapping the regex for an RFC-compliant parser that test needed to have it's assertion reversed. I'll push that again.

**Pull request merged**
