### PR TITLE
Added 'hideLabel' option

### PR DESCRIPTION
**Pull request by alvitoraidhy**

### CODE REVIEW

**Review by ljharb — COMMENTED** [review]
What's the use case for making the form inaccessible by hiding the label?

**Comment by icarus213** [comment]
In my case, I don't need labels because placeholders are enough for me

Also this doesn't really conflict with anything and I noticed that it was already requested so I don't see why not

**Comment by ljharb** [comment]
Placeholders are not mean to be used as labels; only as example input. It’s a UX antipattern to abuse placeholders for infield labels, and it goes against the standard as well.

This seems related to https://github.com/caolan/forms/issues/94#issuecomment-36194091 - i don’t mind a way to get only the input if there’s a need, but i don’t want to encourage necessary labels to be hidden.

**Comment by icarus213** [comment]
Okay, but this also makes it possible to render the labels separately, like python's wtforms (although the div's still there). The option can be named inputOnly instead of hideLabel if you want.

**Pull request closed without merging**
